#!/bin/sh

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --disable-external --url-ignore '/fonts.gstatic.com/,https://fonts.googleapis.com/'
bundle exec rubocop -D --config .rubocop.yml
# bundle exec script/validate-html
bundle exec ruby script/validate-html

gem build jekyll-theme-cayman.gemspec
